### ISSUE TITLE
Wavelet computation is broken

### ISSUE THREAD

**Issue by nperraud** [ltfat/ltfat#105]
I think one of the last commit broke the wavelet modules... See the trace below.
```
>> fwt2(cameraman,'db8',4)
Error using nargout
Error: File: wfilt_db.m Line: 103 Column: 20
()-indexing must appear last in an index expression.

Error in fwtinit (line 289)
wfiltNargout = nargout(tmpFile);

Error in fwt2 (line 74)
w = fwtinit(w);
```

**Comment by susnak** [comment]
Hi, I cannot reproduce the behavior, but I have only tried on Octave. Could you please double check with the latest commit?

**Comment by nholighaus** [comment]
I have the same issue. It's caused by temporary vector indexing in the expression "sort(r, 'descend')(:)" (in line 103). This works in octave, but not Matlab. Is there ever a case where "r" is not a vector? Otherwise "sort(r, 'descend')" is entirely sufficient.

There is another issue in line 128: "c /= norm(c);" likely works in octave, but in Matlab, it should be "c = c ./ norm(c);"

Can you comment? I can make the change and push, if you approve.

**Comment by susnak** [comment]
By all means, please go ahead.
Zdenek

**Comment by allthatsounds** [comment]
done.
