### ISSUE TITLE
Question about twisted convolution implementation

### ISSUE THREAD

**Issue by ecm0** [ltfat/ltfat#109]
Dear ltfat developers,

the twisted convolution has a very compact implementation in tconv.m
that combines col2diag() and FFT.

https://github.com/ltfat/ltfat/blob/5a376ee3c77e94c383d80becfe4bcc5cdf1e9a15/gabor/tconv.m#L75

Would it be possible to have a pointer to where this is coming from?

Thanks and best regards,
Eric Chassande-Mottin

**Comment by nholighaus** [comment]
Dear Eric,I cannot give you a full answer, or a literature source, right away, but will look into it. My semi-educated guess would be that the twisted convolution can be rewritten in terms of symplectic Fourier transforms, which can be implemented by combining col2diag and fft if I remember correctly. It's been some years since I've looked at this :-(Give me a few days and I'll find a more satisfactory answer.Nicki

**Comment by psoenderg** [comment]
I think I got the definition from one of Monikas papers, not quite sure though.

Cheers, Peter 
-- 
Dette er sendt fra min mobiltelefon. Undskyld at jeg fatter mig i korthed.

**Comment by ecm0** [comment]
Dear Nicki and Peter,

thank you for the quick reply. I'll look up Monika Dörfler's papers. I've noticed several papers with Bruno Torresani about Gabor multipliers. Is this the source? Does Monika address the discrete case? Or have you done this part of the work yourself? Any help is very welcome.

Thank you again,
É CM
