### ISSUE TITLE
Should we also move ltfatnotes to github?

### ISSUE THREAD

**Issue by susnak** [ltfat/ltfat#29]

**Comment by susnak** [comment]
It is a public repository, so probably not.

**Comment by susnak** [comment]
One can request free private repositories for academic purposes.
I will ask for some.

**Comment by psoenderg** [comment]
Sure, go ahead! I used Subversion for it, because svn makes it possible to check out and work with one note only.  I don' t think that is possible with Git (you check out the whole package instead), but perhaps something has changed or we can just ignore the problem. I don't know the size of the full repository actually.

**Comment by susnak** [comment]
I have found git submodule and git subtree so maybe it is possible to work with just one note at once.

**Comment by susnak** [comment]
Ok, so git sparse-checkout should do the trick:
http://jasonkarns.com/blog/subdirectory-checkouts-with-git-sparse-checkout/

**Comment by psoenderg** [comment]
Perfect! Then I think it is time to say completely goodbye to subversion.

**Comment by susnak** [comment]
It looks like we will not get a private repository any time soon.
