### ISSUE TITLE
Help with testing release 2.3.0

### ISSUE THREAD

**Issue by susnak** [ltfat/ltfat#80]
Dear watchers and stargazers,

I would wery much appreciate your help with testing the new release 2.3.0. I made some significant changes in the C code so it would be nice to know if everything still works as it should. The most valuable feedback is from Mac users as I do not have access to a Mac machine.

Please report your results as a reply to this ticket. Please also include your OS and whether you are using Matlab or GNU Octave.

Matlab users:
-----------------

1) Get the appropriate release package from https://github.com/ltfat/ltfat/releases/tag/2.3.0

2)  Make sure that your regular LTFAT installation is not in the search path and run the following:
```
ltfatstart
ltfatmex % (not on Windows)
ltfatmex playrec % (not on Windows)
test_all_ltfat % This might take a long time
```
3) Also run 
```
demo_blockproc_slidingsgram(gspi); 
```
4) And this too
```
mulaclab(gspi,44100);
```
This should open GUI and is should be possible to select some area using the mouse (right click finishes the selection). Then click the Apply button and a second plot should appear with the selected area removed. 

GNU Octave users:
-------------------------
1) Use pkg to install ltfat-2.3.0-of.tar.gz
```
pkg install ltfat-2.3.0-of.tar.gz
pkg load ltfat
```
2) Run
```
test_all_ltfat % This will just take forever
```
Also run 3) and 4) as in the Matlab case.

**Comment by nperraud** [comment]
Compiling on mac leads to the following error
```
>> ltfatstart
LTFAT version 2.3.0. Copyright 2005-2018 Peter L. Søndergaard. For help, please type "ltfathelp". LTFAT is using the script language backend.
(Your global and persistent variables have just been cleared. Sorry.)
ltfatmex
========= Compiling libltfat ==============
Done.
========= Compiling MEX interfaces ========
   ...using libmwfftw3.3.dylib from Matlab installation.
   ...using libmwfftw3f.3.dylib from Matlab installation.
Error using ltfatmex (line 282)
Failed to build MEX interfaces: cc -shared -fPIC -O3 -Wall -std=c99 -I../libltfat/thirdparty
-I../libltfat/include -I../libltfat/include/ltfat -I/Applications/MATLAB_R2017a.app/extern/include
-o vect2cell.mexmaci64 vect2cell.c ../lib/libltfat.a -lc -lm
-L"/Applications/MATLAB_R2017a.app/bin/maci64" -lmex -lmx -lmwblas -lmwlapack
/Applications/MATLAB_R2017a.app/bin/maci64/libmwfftw3.3.dylib
/Applications/MATLAB_R2017a.app/bin/maci64/libmwfftw3f.3.dylib
In file included from vect2cell.c:16:
./ltfat_mex_template_helper.h:112:10: fatal error: 'ltfat.h' file not found
#include "ltfat.h"
         ^~~~~~~~~
1 error generated.
make: *** [vect2cell.mexmaci64] Error 1
```

**Comment by susnak** [comment]
Hi Nathanael, 
ahh, I forgot to fix the include path. Could you please try again? The release is updated.

**Comment by nholighaus** [comment]
I'll download and run the tester today, but since my setup is basically yours, I expect everything to go smoothly.Nicki-------- Originalnachricht --------Betreff: Re: [ltfat/ltfat] Help with testing release 2.3.0 (#80)Von: Zdeněk Průša An: ltfat/ltfat Cc: Subscribed Hi Nathanael,
ahh, I forgot to fix the include path. Could you please try again? The release is updated.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ltfat/ltfat","title":"ltfat/ltfat","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ltfat/ltfat"}},"updates":{"snippets":[{"icon":"PERSON","message":"@susnak in #80: Hi Nathanael, \r\nahh, I forgot to fix the include path. Could you please try again? The release is updated."}],"action":{"name":"View Issue","url":"https://github.com/ltfat/ltfat/issues/80#issuecomment-379165081"}}}
