### ISSUE TITLE
wignervilledist of a circular Gaussian is not circular

### ISSUE THREAD

**Issue by susnak** [ltfat/ltfat#81]
The following should be circular:
```
c = wignervilledist(fftshift(exp(i*2*pi*(0:1023)'*0.25).*pgauss(1024,1)));
plotquadtfdist(c,'dynrange',60);axis square;zoom(6)
```
and it is not. It seems it is off by a factor of 2 since the following is circular:
```
c = wignervilledist(fftshift(exp(i*2*pi*(0:1023)'*0.25).*pgauss(1024,2)));
plotquadtfdist(c,'dynrange',60);axis square;zoom(6)
```
Also there should be a flag 'complex' which would allow treating real inputs as complex.

**Comment by allthatsounds** [comment]
Incidentally, I came across this the other day. The trouble is that the continuous WVD is defined for time-lags tao/2 and when discretizing those, one somehow needs to decide how to handle this. In our implementation, tao/2 is assumed as integer tao, yet the WVD is still only evaluated over the signal length (instead of the range 2signallength -1). I looked around and it seems that this generally is the most common general purpose approximation out there (most likely also because it's relatively cheap, computationally), so I'd leave it as it is.
