### ISSUE TITLE
ltfat 2.3.0 - Unable to install

### ISSUE THREAD

**Issue by renatoyamane** [ltfat/ltfat#85]
OS: Windows 10
Octave 4.4.0

pkg update 
unpack: unarchiving program exited with status: 2 
tar: ltfat/src/modules/libltfat/doc/project.bib: Cannot create symlink to '_/home/**susnak**/dev/ltfat/mat2doc/project.bib_':
No such file or directory 
tar: Exiting with failure status due to previous errors 
error: called from 
unpack at line 257 column 5 
untar at line 47 column 5 
install at line 81 column 9 
pkg at line 437 column 9 
pkg at line 598 column 11

https://savannah.gnu.org/bugs/?53865

**Comment by T-o-m-m-i** [comment]
I can't seem to install ltfat 2.3.0 either. OS: Win10, Octave 4.4.0.
Is this a forge, pkg or ltfat thing? Other packages installs just fine.

>> pkg install -forge ltfat
unpack: unarchiving program exited with status: 2
tar: ltfat/src/modules/libltfat/doc/project.bib: Cannot create symlink to `
/home/susnak/dev/ltfat/mat2doc/project.bib': No such file or directory
tar: Exiting with failure status due to previous errors
error: called from
    unpack at line 257 column 5
    untar at line 47 column 5
    install at line 81 column 9
    pkg at line 437 column 9

**Comment by susnak** [comment]
Hi, it is a ltfat thing. Apperently the archive cannot be unpacked if there is a broken symlink. I will submit a new release soon.

**Comment by susnak** [comment]
Fixed in 2.3.1
