### ISSUE TITLE
How to treat zero-bandwith filters

### ISSUE THREAD

**Issue by susnak** [ltfat/ltfat#94]
The following produces a zero bandwidth filter g{1}
```
[f,fs]=greasy;  % Get the test signal
[g,a,fc,L]=audfilters(fs,length(f),'uniform','M',100);
c=filterbank(f,g,a);
```
then c{1} is a zero vector.
Would it make sense to remove that filter at the end on audfilters?

**Comment by nholighaus** [comment]
Removing the filters is reasonable, but if we do, audfilters should surely print a warning, as such behavior is not described in the accompanying paper. Users will ask themselves why they get less filters than requested and why the minimum frequency is not what they think it is. I do think the paper hints at the fact that the filters might be trivial, but not their removal.Cheers,Nicki-------- Originalnachricht --------Betreff: Re: [ltfat/ltfat] How to treat zero-bandwith filters (#94)Von: Zdeněk Průša An: ltfat/ltfat Cc: Subscribed g{1}

ans = 

  struct with fields:

           H: @(L)0
        foff: @(L)0
    realonly: 0
       delay: 0
          fs: 16000


—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ltfat/ltfat","title":"ltfat/ltfat","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/ltfat/ltfat"}},"updates":{"snippets":[{"icon":"PERSON","message":"@susnak in #94: ```\r\ng{1}\r\n\r\nans = \r\n\r\n  struct with fields:\r\n\r\n           H: @(L)0\r\n        foff: @(L)0\r\n    realonly: 0\r\n       delay: 0\r\n          fs: 16000\r\n```"}],"action":{"name":"View Issue","url":"https://github.com/ltfat/ltfat/issues/94#issuecomment-404764020"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ltfat/ltfat/issues/94#issuecomment-404764020",
"url": "https://github.com/ltfat/ltfat/issues/94#issuecomment-404764020",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [ltfat/ltfat] How to treat zero-bandwith filters (#94)",
"sections": [
{
"text": "",
"activityTitle": "**Zdeněk Průša**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@susnak",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"ltfat/ltfat\",\n\"issueId\": 94,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"ltfat/ltfat\",\n\"issueId\": 94\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/ltfat/ltfat/issues/94#issuecomment-404764020"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 356121658\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by susnak** [comment]
Ok, I leave them in. I just fixed some functions which were broken by this.
