### ISSUE TITLE
DFRACFT - fftshift issue

### ISSUE THREAD

**Issue by s-sajid-ali** [ltfat/ltfat#97]
I'm trying to use DFRACT to gradually increase the order of the transform from 0 to 1 which should give me the input signal at 0 and full FT at 1. But, the results are shifted only for higher orders but not the lower ones. 

For lower orders , 
`>> plot(abs(dfracft(f,0.0)))`

![image](https://user-images.githubusercontent.com/30510036/47565779-356e3b00-d8ef-11e8-8bef-c2f4203bbbf2.png)

But for higher orders,  
`>> plot(abs(dfracft(f,1.0)))`

![image](https://user-images.githubusercontent.com/30510036/47565845-75352280-d8ef-11e8-8cd8-7797173c0a01.png)

Which is fftshifted although the first one isn't. What causes this inconsistency ?

**Comment by s-sajid-ali** [comment]
You're right : 

The function f is the usual rect function. 
`>> plot(f)`

![image](https://user-images.githubusercontent.com/30510036/47592944-0e3d5b00-d93b-11e8-8d17-3c8d4d0f9e7d.png)

What I wanted to recreate was this plot from [1](https://ieeexplore.ieee.org/document/757221)

![image](https://user-images.githubusercontent.com/30510036/47593005-5eb4b880-d93b-11e8-9241-89821f66ad37.png)


But using the ltfat package : 

orders of 0.0065, 0.255,0.5,1 (all with p=50 ):

![image](https://user-images.githubusercontent.com/30510036/47593469-14ccd200-d93d-11e8-9532-e0192eb1f3cd.png)

While the low order result matches, the high order (=1 or pi/4 depending on how it's defined) result is shifted. This problem doesn't occur when using [this code](https://nalag.cs.kuleuven.be/research/software/FRFT/Disfrft.m) which uses the same hermbasis to create the eigenvectors. I haven't looked too deep into the helper functions that the ltfat-dfracft uses but I wonder if that causes the issue. 

Using Disfrft (which as I restate uses the same eigenvectors as given by hermbasis):

`>> plot(abs(Disfrft(f,0.01,50)))`

![image](https://user-images.githubusercontent.com/30510036/47593643-a1779000-d93d-11e8-87fc-ae155373a1e7.png)

`>> plot(abs(Disfrft(f,1,50)))`

![image](https://user-images.githubusercontent.com/30510036/47593693-d4ba1f00-d93d-11e8-8e9a-a82143dab057.png)

**Comment by nholighaus** [comment]
Apparently that other code you sent uses the convention that the convention that the central index of the given vector corresponds to position 0 in any domain, time, frequency and in between.In LTFAT, the 0 position is at vector index 1, in agreement with how the FFT command works. To reproduce the plots you want, use e.g.f=firwin('rect',200); %Create rect winf=fir2long(f,500); % pad to desired lengthThen, use plot(fftshift(...)) instead of plot for plotting your results to place the 0 position in the center of the plot. The code behaves exactly as expected. Your problem is that in the LTFAT convention, your input is interpreted as a shifted rect function. Maybe it helps to look at how firwin always produces windows that are centered around index 1, such that the FFT of a real, symmetric function is again real, symmetric.-------- Originalnachricht --------Betreff: Re: [ltfat/ltfat] DFRACFT - fftshift issue (#97)Von: Sajid Ali An: ltfat/ltfat Cc: nholighaus ,Comment You're right :
The function f is the usual rect function.
>> plot(f)

What I wanted to recreate was this plot from 1

But using the ltfat package :
orders of 0.0065, 0.255,0.5,1 (all with p=50 ):

While the low order result matches, the high order (=1 or pi/4 depending on how it's defined) result is shifted. This problem doesn't occur when using this code which uses the same hermbasis to create the eigenvectors. I haven't looked too deep into the helper functions that the ltfat-dfracft uses but I wonder if that causes the issue.
Using Disfrft (which as I restate uses the same eigenvectors as given by hermbasis):
>> plot(abs(Disfrft(f,0.01,50)))

>> plot(abs(Disfrft(f,1,50)))


—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ltfat/ltfat","title":"ltfat/ltfat","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/ltfat/ltfat"}},"updates":{"snippets":[{"icon":"PERSON","message":"@s-sajid-ali in #97: You're right : \r\n\r\nThe function f is the usual rect function. \r\n`\u003e\u003e plot(f)`\r\n\r\n![image](https://user-images.githubusercontent.com/30510036/47592944-0e3d5b00-d93b-11e8-8d17-3c8d4d0f9e7d.png)\r\n\r\nWhat I wanted to recreate was this plot from [1](https://ieeexplore.ieee.org/document/757221)\r\n\r\n![image](https://user-images.githubusercontent.com/30510036/47593005-5eb4b880-d93b-11e8-9241-89821f66ad37.png)\r\n\r\n\r\nBut using the ltfat package : \r\n\r\norders of 0.0065, 0.255,0.5,1 (all with p=50 ):\r\n\r\n![image](https://user-images.githubusercontent.com/30510036/47593469-14ccd200-d93d-11e8-9532-e0192eb1f3cd.png)\r\n\r\nWhile the low order result matches, the high order (=1 or pi/4 depending on how it's defined) result is shifted. This problem doesn't occur when using [this code](https://nalag.cs.kuleuven.be/research/software/FRFT/Disfrft.m) which uses the same hermbasis to create the eigenvectors. I haven't looked too deep into the helper functions that the ltfat-dfracft uses but I wonder if that causes the issue. \r\n\r\nUsing Disfrft (which as I restate uses the same eigenvectors as given by hermbasis):\r\n\r\n`\u003e\u003e plot(abs(Disfrft(f,0.01,50)))`\r\n\r\n![image](https://user-images.githubusercontent.com/30510036/47593643-a1779000-d93d-11e8-87fc-ae155373a1e7.png)\r\n\r\n`\u003e\u003e plot(abs(Disfrft(f,1,50)))`\r\n\r\n![image](https://user-images.githubusercontent.com/30510036/47593693-d4ba1f00-d93d-11e8-8e9a-a82143dab057.png)\r\n\r\n\r\n\r\n\r\n"}],"action":{"name":"View Issue","url":"https://github.com/ltfat/ltfat/issues/97#issuecomment-433551206"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ltfat/ltfat/issues/97#issuecomment-433551206",
"url": "https://github.com/ltfat/ltfat/issues/97#issuecomment-433551206",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [ltfat/ltfat] DFRACFT - fftshift issue (#97)",
"sections": [
{
"text": "",
"activityTitle": "**Sajid Ali**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@s-sajid-ali",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"ltfat/ltfat\",\n\"issueId\": 97,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"ltfat/ltfat\",\n\"issueId\": 97\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/ltfat/ltfat/issues/97#issuecomment-433551206"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 401636594\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by s-sajid-ali** [comment]
Got it. Thank you !
